Added reference to npm and table of options to the README.
marekdedic/imagelightbox pull request #489
Opened 2022-12-14 12:22 UTC by pmagictech

Thanks for all the work done on this library. It was really helpful to me. But I spent some time trying to set it up for my project. I am creating this PR to help others understand how to set it up quickly. I am thinking of updating the documentation page after this.

2022-12-14 17:37 UTC, marekdedic commented
Hi, thanks for the PR, I'll take a look at it ;)

2023-01-12 10:49 UTC, marekdedic requested changes

2023-01-12 10:49 UTC, marekdedic commented on README.md
> +npm install jquery imagelightbox
`npm install --save` would probably be better ;)

2023-01-12 10:49 UTC, marekdedic commented on README.md
> +After that include imagelightbox.css and imagelightbox(.min).js to your page.
The CSS is now also available minified

2023-01-12 10:49 UTC, marekdedic commented on README.md
> +After that include imagelightbox.css and imagelightbox(.min).js to your page.
Also, it would be good to tell people the exact path - mostly because they should use the files from the `dist` directory

2023-01-12 10:49 UTC, marekdedic commented on README.md
> +|allowTypes|'png&#124;jpg&#124;jpeg&#124;gif'|string|use empty string to allow any file type|
`allowedTypes`

2023-01-12 10:49 UTC, marekdedic commented on README.md
> +
This should probably just replace the code snippet above - just reference there that the constructor takes options as a parameter and then list them in this table?

2023-01-12 10:49 UTC, marekdedic commented
Thanks for the PR, I have a few changes I'd like to make, do you still have the time to look at this?

2024-03-28 20:21 UTC, marekdedic commented
Hi @pmagictech, thanks once again for the PR, the project has had a lot of changes recently, so rather than rebasing your PR, I took the changes and re-applied them as part of #934. Hope you don't mind.

2024-03-28 20:21 UTC, closed without merging

2024-03-30 04:17 UTC, pmagictech commented
> Hi @pmagictech, thanks once again for the PR, the project has had a lot of changes recently, so rather than rebasing your PR, I took the changes and re-applied them as part of #934. Hope you don't mind.

No, I don't mind. I am happy that the documentation is much better now. Well done.